import { Button } from "@mui/material"
import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>商品管理</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>商品管理</h1>
        <Link href={"/order/create"}>
          <Button variant="outlined">新規発注</Button>
        </Link>
      </main>
    </>
  )
}
